-- Migración V1: Crear tabla clientes
-- Fecha: 2026-05-12
-- Descripción: Crear tabla base de clientes con todos los campos necesarios

CREATE TABLE clientes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    rut VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255),
    telefono VARCHAR(255),
    direccion VARCHAR(255),
    comuna VARCHAR(255),
    region VARCHAR(255),
    fecha_registro DATE
);

-- Crear índice para optimizar búsquedas por RUT
CREATE INDEX idx_cliente_rut ON clientes(rut);